### ISSUE TITLE
Translation of fork as "分支" in Chinese has ambiguity

### ISSUE THREAD

**Issue by xxl-cc** [gitblit-org/gitblit#1448]
In version 1.9, the fork tab of the tab page should be translated as "分支" in simplified Chinese, which should not be appropriate and may be confused with the Git branch. It is recommended to translate it into version 1.8's "派生" or "复刻"。

**Comment by flaix** [comment]
So which one of the two should it be? I cannot decide that myself.

**Comment by xxl-cc** [comment]
I prefer to translate 'fork' as' 派生 '。

**Comment by flaix** [comment]
This was changed in PR #1367 which changed from '派生' to '分支'. So you are saying both are not good, and instead it should be '复刻'?

Should I simply exchange every occurrence of '分支' with '复刻'? Because the change in the PR did change more than just these characters. Example: '已派生' changed to '已建立分支'. So you are saying this should be '已建立复刻' instead?
